modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "cavebiomes"
version = "${version}"
displayName = "CaveBiomeAPI"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.cavebiomes]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cavebiomes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"